sudo: false

cache:
  - pip

dist: trusty

language: python

python:
  - '2.7'
  - '3.6'

before_install:
  - pip install hacking
  - flake8 .

install:
  - pip install .

script:
  - ./.travis.sh

after_success:
  - |
    if [ "$TRAVIS_BRANCH" = "master" ]; then
      ./generate_readme.py > README.md
      ./.travis_push.sh README.md
    fi

branches:
  only:
    - master
